name: pychemkit
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - libffi=3.4.4
  - openssl=3.0.16
  - pip=25.1
  - python=3.10.14
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - annotated-types==0.7.0
      - colorama==0.4.6
      - deprecated==1.2.18
      - greenlet==3.2.2
      - mendeleev==1.0.0
      - numpy==1.26.4
      - pandas==2.2.3
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pyfiglet==0.8.post1
      - pygments==2.19.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - six==1.17.0
      - sqlalchemy==2.0.40
      - typing-extensions==4.13.2
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - wrapt==1.17.2
      - epam-indigo>=1.16
